name: 'Auto-version: Next Version'
description: 'Uses git tags and a version base to find the next patch version'
author: 'Kevin Galligan'

inputs:
  versionBase:
    description: 'Base version value. Must be x.y.'
    required: true

outputs:
  nextVersion:
    description: 'Next version'

runs:
  using: node20
  main: dist/index.js
